export const realSchemesData = [
  {
    id: 's1',
    name: 'PM Kisan Samman Nidhi',
    ministry: 'Ministry of Agriculture',
    description: 'Financial benefit of Rs. 6000 per year to eligible farmer families. The amount is paid in three equal installments of Rs. 2000 each, directly into the bank accounts of the beneficiaries.',
    benefits: '₹6,000 per year in 3 installments',
    eligibility: { occupations: ['farmer'], gender: 'all' },
    documents: ['Aadhaar Card', 'Land Records', 'Bank Account Details'],
    deadline: '2026-06-30',
    applyLink: 'https://pmkisan.gov.in',
    tags: ['Agriculture', 'Financial Aid'],
    views: 45200,
    saves: 12300,
  },
  {
    id: 's2',
    name: 'Ayushman Bharat - PMJAY',
    ministry: 'Ministry of Health',
    description: 'Health insurance scheme providing coverage of Rs. 5 lakh per family per year for secondary and tertiary care hospitalization to over 12 crore poor and vulnerable families.',
    benefits: '₹5 Lakh health insurance per family per year',
    eligibility: { maxIncome: 500000, gender: 'all' },
    documents: ['Aadhaar Card', 'Ration Card', 'Income Certificate'],
    applyLink: 'https://pmjay.gov.in',
    tags: ['Health', 'Insurance'],
    views: 38700,
    saves: 9800,
  },
  {
    id: 's3',
    name: 'PM Awas Yojana - Gramin',
    ministry: 'Ministry of Rural Development',
    description: 'Provides financial assistance for construction of pucca house to all eligible rural households who are houseless or living in kutcha or dilapidated houses.',
    benefits: '₹1.20 Lakh (Plains) / ₹1.30 Lakh (Hilly areas)',
    eligibility: { maxIncome: 300000, gender: 'all', categories: ['SC', 'ST', 'OBC', 'General'] },
    documents: ['Aadhaar Card', 'BPL Card', 'Income Certificate', 'Land Documents'],
    deadline: '2026-12-31',
    applyLink: 'https://pmayg.nic.in',
    tags: ['Housing', 'Rural'],
    views: 32100,
    saves: 8500,
  },
  {
    id: 's4',
    name: 'Sukanya Samriddhi Yojana',
    ministry: 'Ministry of Finance',
    description: "A small deposit scheme for the girl child under the 'Beti Bachao Beti Padhao' campaign. Offers one of the highest interest rates among government savings schemes.",
    benefits: 'High interest rate of 8.2% per annum',
    eligibility: { maxAge: 10, gender: 'female' },
    documents: ["Birth Certificate", "Parent's Aadhaar Card", "Address Proof"],
    applyLink: 'https://www.india.gov.in',
    tags: ['Savings', 'Girl Child', 'Education'],
    views: 28500,
    saves: 11200,
  },
  {
    id: 's5',
    name: 'National Pension Scheme',
    ministry: 'Ministry of Finance',
    description: 'Voluntary defined contribution pension scheme providing old-age income with reasonable market-based returns.',
    benefits: 'Tax benefits + pension after 60 years of age',
    eligibility: { minAge: 18, maxAge: 70, gender: 'all' },
    documents: ['Aadhaar Card', 'PAN Card', 'Bank Account', 'Photograph'],
    applyLink: 'https://www.npscra.nsdl.co.in',
    tags: ['Pension', 'Retirement', 'Tax Benefit'],
    views: 22400,
    saves: 6700,
  },
  {
    id: 's6',
    name: 'PM Mudra Yojana',
    ministry: 'Ministry of Finance',
    description: 'Provides loans up to ₹10 Lakh to non-corporate, non-farm small/micro enterprises for income generating activities.',
    benefits: 'Loans up to ₹10 Lakh without collateral',
    eligibility: { minAge: 18, gender: 'all', occupations: ['self-employed', 'business', 'entrepreneur'] },
    documents: ['Aadhaar Card', 'Business Plan', 'Address Proof', 'Identity Proof'],
    applyLink: 'https://www.mudra.org.in',
    tags: ['Business', 'Loan', 'Entrepreneurship'],
    views: 35600,
    saves: 9200,
  },
  {
    id: 's7',
    name: 'PM Ujjwala Yojana',
    ministry: 'Ministry of Petroleum',
    description: 'Free LPG connections provided to women belonging to BPL households to ensure smokeless kitchens and promote health.',
    benefits: 'Free LPG Connection and first refill',
    eligibility: { gender: 'female', minAge: 18, maxIncome: 200000 },
    documents: ['Aadhaar Card', 'BPL Ration Card', 'Passport Photo', 'Bank Account'],
    applyLink: 'https://www.pmuy.gov.in',
    tags: ['Women', 'Health', 'Rural'],
    views: 41200,
    saves: 8300,
  },
  {
    id: 's8',
    name: 'Stand-Up India Scheme',
    ministry: 'Ministry of Finance',
    description: 'Facilitates bank loans between 10 lakh and 1 Crore to at least one SC or ST borrower and at least one woman borrower per bank branch for setting up a greenfield enterprise.',
    benefits: 'Loans from ₹10 Lakh to ₹1 Crore',
    eligibility: { minAge: 18, categories: ['SC', 'ST'], gender: 'female', occupations: ['entrepreneur', 'business'] },
    documents: ['Aadhaar Card', 'Project Report', 'Caste Certificate', 'Bank Account'],
    applyLink: 'https://www.standupmitra.in',
    tags: ['Business', 'Loan', 'Women', 'SC/ST'],
    views: 15300,
    saves: 4100,
  },
  {
    id: 's9',
    name: 'PM Fasal Bima Yojana',
    ministry: 'Ministry of Agriculture',
    description: 'Comprehensive crop insurance from pre-sowing to post-harvest losses against natural non-preventable risks.',
    benefits: 'Crop insurance with very low premium (1.5% to 2%)',
    eligibility: { occupations: ['farmer'] },
    documents: ['Aadhaar Card', 'Land Records', 'Sowing Certificate', 'Bank Account'],
    applyLink: 'https://pmfby.gov.in',
    tags: ['Agriculture', 'Insurance', 'Farmer'],
    views: 29400,
    saves: 6200,
  },
  {
    id: 's10',
    name: 'Atal Pension Yojana',
    ministry: 'Ministry of Finance',
    description: 'A guaranteed pension scheme primarily for workers in the unorganized sector to secure their future.',
    benefits: 'Guaranteed pension of ₹1000 to ₹5000 per month after 60 years',
    eligibility: { minAge: 18, maxAge: 40, occupations: ['unorganized sector', 'laborer', 'self-employed'] },
    documents: ['Aadhaar Card', 'Bank Account'],
    applyLink: 'https://npscra.nsdl.co.in/scheme-details.php',
    tags: ['Pension', 'Savings', 'Unorganized Sector'],
    views: 18900,
    saves: 5300,
  },
  {
    id: 's11',
    name: 'National Scholarship Portal (Pre/Post Matric)',
    ministry: 'Ministry of Minority Affairs / Social Justice',
    description: 'Provides scholarships to meritorious students belonging to economically weaker sections and minority communities.',
    benefits: 'Financial assistance for tuition fees and maintenance allowance',
    eligibility: { occupations: ['student'], maxIncome: 250000, categories: ['SC', 'ST', 'OBC', 'Minority'] },
    documents: ['Aadhaar Card', 'Income Certificate', 'Caste Certificate', 'Student ID/Marksheet'],
    applyLink: 'https://scholarships.gov.in',
    tags: ['Education', 'Scholarship', 'Students'],
    views: 52000,
    saves: 15400,
  },
  {
    id: 's12',
    name: 'PM Jeevan Jyoti Bima Yojana',
    ministry: 'Ministry of Finance',
    description: 'A one-year life insurance scheme renewable from year to year offering coverage for death due to any reason.',
    benefits: 'Life cover of ₹2 Lakhs at ₹436/year premium',
    eligibility: { minAge: 18, maxAge: 50 },
    documents: ['Aadhaar Card', 'Bank Account Details'],
    applyLink: 'https://jansuraksha.gov.in',
    tags: ['Insurance', 'Life Cover'],
    views: 22100,
    saves: 4500,
  },
  {
    id: 's13',
    name: 'PM Suraksha Bima Yojana',
    ministry: 'Ministry of Finance',
    description: 'Accident insurance scheme offering accidental death and disability cover for a very low annual premium.',
    benefits: 'Accident cover of ₹2 Lakhs at ₹20/year premium',
    eligibility: { minAge: 18, maxAge: 70 },
    documents: ['Aadhaar Card', 'Bank Account Details'],
    applyLink: 'https://jansuraksha.gov.in',
    tags: ['Insurance', 'Accident Cover'],
    views: 24500,
    saves: 4900,
  },
  {
    id: 's14',
    name: 'PM Vishwakarma Yojana',
    ministry: 'Ministry of MSME',
    description: 'Support traditional artisans and craftspeople in scaling up their businesses with training, toolkit incentives, and credit.',
    benefits: '₹15,000 for toolkit, ₹500/day during training, collateral-free loans up to ₹3 Lakh',
    eligibility: { minAge: 18, occupations: ['artisan', 'craftsman', 'weaver', 'carpenter', 'blacksmith'] },
    documents: ['Aadhaar Card', 'Bank Account', 'Skill Certificate/Proof of Trade'],
    applyLink: 'https://pmvishwakarma.gov.in',
    tags: ['MSME', 'Artisan', 'Loan', 'Skill'],
    views: 31000,
    saves: 8800,
  },
  {
    id: 's15',
    name: 'PM Matru Vandana Yojana',
    ministry: 'Ministry of Women and Child Development',
    description: 'Maternity benefit program offering cash incentives to pregnant women and lactating mothers for partial wage compensation.',
    benefits: '₹5,000 in three installments (₹6000 for second girl child)',
    eligibility: { gender: 'female', minAge: 19 },
    documents: ['Aadhaar Card', 'MCP Card from AWC', 'Bank Account'],
    applyLink: 'https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana',
    tags: ['Women', 'Maternity', 'Health'],
    views: 26000,
    saves: 6500,
  },
  {
    id: 's16',
    name: 'PM SVANidhi',
    ministry: 'Ministry of Housing and Urban Affairs',
    description: 'Special micro-credit facility for street vendors to resume their livelihoods affected by COVID-19 lockdowns.',
    benefits: 'Working capital loan starting at ₹10,000 (up to ₹50,000 in tranches) + interest subsidy',
    eligibility: { occupations: ['street vendor', 'vendor', 'business'] },
    documents: ['Aadhaar Card', 'Certificate of Vending', 'Bank Account'],
    applyLink: 'https://pmsvanidhi.mohua.gov.in',
    tags: ['Loan', 'Urban', 'Livelihood'],
    views: 19500,
    saves: 4100,
  },
  {
    id: 's17',
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
    ministry: 'Ministry of Skill Development',
    description: 'Aims to enable Indian youth to take up industry-relevant skill training to secure a better livelihood.',
    benefits: 'Free skill training and certification, placement assistance',
    eligibility: { minAge: 15, maxAge: 45, occupations: ['student', 'unemployed', 'youth'] },
    documents: ['Aadhaar', 'School/College Leaving Certificate', 'Bank Account'],
    applyLink: 'https://www.pmkvyofficial.org',
    tags: ['Skill', 'Youth', 'Employment'],
    views: 34000,
    saves: 9500,
  },
  {
    id: 's18',
    name: 'Mahatma Gandhi NREGA',
    ministry: 'Ministry of Rural Development',
    description: 'Guarantees 100 days of wage employment in a financial year to rural households whose adult members volunteer to do unskilled manual work.',
    benefits: '100 days guaranteed wage employment',
    eligibility: { minAge: 18, occupations: ['laborer', 'unemployed', 'farmer'] },
    documents: ['Aadhaar Card', 'Job Card', 'Bank Account'],
    applyLink: 'https://nrega.nic.in',
    tags: ['Employment', 'Rural', 'Wages'],
    views: 45000,
    saves: 11000,
  },
  {
    id: 's19',
    name: 'National Scheme of Incentive to Girls for Secondary Education (NSIGSE)',
    ministry: 'Ministry of Education',
    description: 'Promotes girls enrollment in the age group of 14-18 at secondary stage, especially those who passed class 8 and belong to marginalized communities.',
    benefits: 'Amount of ₹3,000 deposited as fixed deposit withdrawable at age 18',
    eligibility: { gender: 'female', maxAge: 16, categories: ['SC', 'ST'], occupations: ['student'] },
    documents: ['Aadhaar Card', 'Birth Certificate', 'Caste Certificate', 'Class 8 Marksheet'],
    applyLink: 'https://scholarships.gov.in',
    tags: ['Education', 'Girls', 'Scholarship'],
    views: 14500,
    saves: 3900,
  },
  {
    id: 's20',
    name: 'Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)',
    ministry: 'Ministry of Rural Development',
    description: 'Placement linked skill development scheme for rural poor youth.',
    benefits: 'Free skilling, uniform, food, and post-placement support',
    eligibility: { minAge: 15, maxAge: 35, occupations: ['youth', 'unemployed'] },
    documents: ['Aadhaar Card', 'BPL Card/Income Certificate', 'Education Certificate'],
    applyLink: 'http://ddugky.gov.in',
    tags: ['Skill', 'Rural', 'Youth'],
    views: 16800,
    saves: 4200,
  },
  {
    id: 's21',
    name: 'Beti Bachao Beti Padhao',
    ministry: 'Ministry of Women and Child Development',
    description: 'Campaign to generate awareness and improve the efficiency of welfare services intended for girls.',
    benefits: 'Awareness and integration of services for education and survival of female child',
    eligibility: { gender: 'female' },
    documents: ['Aadhaar Card', 'Birth Certificate'],
    applyLink: 'https://wcd.nic.in/bbbp-schemes',
    tags: ['Women', 'Girl Child', 'Education'],
    views: 48000,
    saves: 13000,
  },
  {
    id: 's22',
    name: 'Mahila Samman Savings Certificate',
    ministry: 'Ministry of Finance',
    description: 'A one-time small savings scheme for women and girls introduced to encourage investments.',
    benefits: 'Fixed interest rate of 7.5% per annum for a maximum deposit of ₹2 Lakhs over a 2-year tenor',
    eligibility: { gender: 'female' },
    documents: ['Aadhaar Card', 'KYC Documents', 'Bank Account'],
    applyLink: 'https://www.indiapost.gov.in',
    tags: ['Women', 'Savings', 'Investment'],
    views: 22400,
    saves: 6100,
  },
  {
    id: 's23',
    name: 'Janani Suraksha Yojana (JSY)',
    ministry: 'Ministry of Health and Family Welfare',
    description: 'Safe motherhood intervention under the National Health Mission aiming to reduce maternal and neonatal mortality by promoting institutional delivery.',
    benefits: 'Cash assistance up to ₹1400 for rural and ₹1000 for urban post delivery',
    eligibility: { gender: 'female', maxIncome: 150000, categories: ['BPL', 'SC', 'ST'] },
    documents: ['Aadhaar Card', 'BPL Card', 'JCH Card', 'Bank Account'],
    applyLink: 'https://nhm.gov.in',
    tags: ['Health', 'Maternity', 'Women'],
    views: 18500,
    saves: 4000,
  },
  {
    id: 's24',
    name: 'Startup India Seed Fund Scheme',
    ministry: 'Ministry of Commerce and Industry',
    description: 'Financial assistance to startups for proof of concept, prototype development, product trials, market entry, and commercialization.',
    benefits: 'Up to ₹20 Lakhs as grant for validation; up to ₹50 Lakhs for commercialization',
    eligibility: { occupations: ['startup', 'entrepreneur', 'business'] },
    documents: ['DPIIT Recognition Certificate', 'Pitch Deck', 'Business Plan'],
    applyLink: 'https://seedfund.startupindia.gov.in',
    tags: ['Startup', 'Business', 'Innovation'],
    views: 29000,
    saves: 8500,
  },
  {
    id: 's25',
    name: 'Kanya Sumangala Yojana (Uttar Pradesh)',
    ministry: 'Government of Uttar Pradesh',
    description: 'Conditional cash transfer scheme for the girl child in Uttar Pradesh covering stages from birth to graduation.',
    benefits: 'Total assistance of ₹15,000 implemented in 6 phases',
    eligibility: { gender: 'female', states: ['Uttar Pradesh'], maxIncome: 300000 },
    documents: ['Aadhaar Card', 'Birth Certificate', 'Domicile Certificate U.P.', 'Bank Account'],
    applyLink: 'https://mksy.up.gov.in',
    tags: ['Girl Child', 'Education', 'State Scheme'],
    views: 15600,
    saves: 4200,
  },
  {
    id: 's26',
    name: 'Rythu Bandhu Scheme (Telangana)',
    ministry: 'Government of Telangana',
    description: 'Agriculture investment support scheme directly depositing cash in farmer accounts every season.',
    benefits: '₹5,000 per acre per season to support farm investment',
    eligibility: { occupations: ['farmer'], states: ['Telangana'] },
    documents: ['Aadhaar Card', 'Pattadar Passbook', 'Bank Account'],
    applyLink: 'http://rythubandhu.telangana.gov.in',
    tags: ['Agriculture', 'State Scheme', 'Farmer'],
    views: 14200,
    saves: 3800,
  },
  {
    id: 's27',
    name: 'YSR Rythu Bharosa (Andhra Pradesh)',
    ministry: 'Government of Andhra Pradesh',
    description: 'Financial assistance to farmer families, including tenant farmers across the state.',
    benefits: '₹13,500 per year per farmer family',
    eligibility: { occupations: ['farmer'], states: ['Andhra Pradesh'] },
    documents: ['Aadhaar Card', 'Land Documents', 'Bank Account'],
    applyLink: 'https://ysrrythubharosa.ap.gov.in',
    tags: ['Agriculture', 'State Scheme', 'Farmer'],
    views: 13900,
    saves: 3600,
  },
  {
    id: 's28',
    name: 'Chief Minister Employment Generation Programme (CMEGP) Maharashtra',
    ministry: 'Government of Maharashtra',
    description: 'Promotes self-employment and creates new enterprises among youth in Maharashtra.',
    benefits: 'Subsidy of 15% to 35% on project cost (up to ₹50 Lakhs)',
    eligibility: { minAge: 18, maxAge: 45, states: ['Maharashtra'], occupations: ['business', 'entrepreneur', 'unemployed'] },
    documents: ['Aadhaar Card', 'Domicile of Maharashtra', 'Project Report'],
    applyLink: 'https://maha-cmegp.gov.in',
    tags: ['Business', 'State Scheme', 'Youth'],
    views: 11000,
    saves: 3100,
  },
  {
    id: 's29',
    name: 'Sardar Patel Urban Housing Scheme (Gujarat)',
    ministry: 'Government of Gujarat',
    description: 'Affordable housing to lower and middle-income groups in urban areas of Gujarat.',
    benefits: 'Financial assistance and subsidized interest rates for housing',
    eligibility: { maxIncome: 600000, states: ['Gujarat'] },
    documents: ['Aadhaar Card', 'Income Certificate', 'Domicile of Gujarat', 'Bank Account'],
    applyLink: 'https://vuda.co.in',
    tags: ['Housing', 'Urban', 'State Scheme'],
    views: 9500,
    saves: 2400,
  },
  {
    id: 's30',
    name: 'Mukhyamantri Kanya Vivah Yojana (Madhya Pradesh)',
    ministry: 'Government of Madhya Pradesh',
    description: 'Financial assistance provided for the marriage of girls from poor families, destitute widows, or divorced women.',
    benefits: 'Financial help of ₹51,000 to ₹55,000 for marriage expenses',
    eligibility: { minAge: 18, gender: 'female', maxIncome: 200000, states: ['Madhya Pradesh'] },
    documents: ['Aadhaar Card', 'Age Proof', 'Income/BPL Certificate', 'Bank Account'],
    applyLink: 'http://socialjustice.mp.gov.in',
    tags: ['Women', 'Marriage', 'State Scheme'],
    views: 12400,
    saves: 3300,
  }
];
